In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/Shreyas3108/house-price-prediction/master/kc_house_data.csv')
data = df.iloc[:,2:6]
data

price  bedrooms  bathrooms  sqft_living
0      221900.0         3       1.00         1180
1      538000.0         3       2.25         2570
2      180000.0         2       1.00          770
3      604000.0         4       3.00         1960
4      510000.0         3       2.00         1680
...         ...       ...        ...          ...
21608  360000.0         3       2.50         1530
21609  400000.0         4       2.50         2310
21610  402101.0         2       0.75         1020
21611  400000.0         3       2.50         1600
21612  325000.0         2       0.75         1020

[21613 rows x 4 columns]

In [4]:
x = data.iloc[:,1:4].values
x

array([[3.00e+00, 1.00e+00, 1.18e+03],
       [3.00e+00, 2.25e+00, 2.57e+03],
       [2.00e+00, 1.00e+00, 7.70e+02],
       ...,
       [2.00e+00, 7.50e-01, 1.02e+03],
       [3.00e+00, 2.50e+00, 1.60e+03],
       [2.00e+00, 7.50e-01, 1.02e+03]])

In [5]:
y = data.iloc[:,0].values
y

array([221900., 538000., 180000., ..., 402101., 400000., 325000.])

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=0)

In [7]:
print(x.shape)
print(x_train.shape)
print(x_test.shape)

(21613, 3)
(16209, 3)
(5404, 3)


In [8]:
print(y.shape)
print(y_train.shape)
print(y_test.shape)

(21613,)
(16209,)
(5404,)


In [9]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.fit_transform(x_test)

In [10]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [12]:
model.fit(x,y)

LinearRegression()

In [13]:
y_pred = model.predict(x_test)
y_pred

array([64844.77474574, 55169.15089037, 64077.41790975, ...,
       54360.52006956, 59050.56051352, 58553.07227647])

In [14]:
y_test

array([ 297000., 1578000.,  562100., ...,  774950.,  372500.,  599995.])

In [ ]:
import joblib
joblib.dump(model,'House.joblib')

['House.joblib']